name: Install Test
on:
  push:
    paths:
      - 'install.sh'
  pull_request:
    paths:
      - 'install.sh'

jobs:
  test-install:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: ['x86_64', 'arm64']
        os: ['ubuntu:20.04', 'debian:10']
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Test install.sh in Docker container
        run: |
          echo "Testing on ${{ matrix.os }} (${{ matrix.arch }})"
          docker buildx build --load \
            --platform=linux/${{ matrix.arch }} \
            --build-arg BASE_IMAGE=${{ matrix.os }} \
            -t test-install:${{ matrix.arch }} \
            -f Dockerfile.test .
          docker run --rm test-install:${{ matrix.arch }} -h