name: GitHub Release CI
on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v4
        with:
          go-version: stable
      - uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  test-install:
    runs-on: ubuntu-latest
    needs: release
    strategy:
      fail-fast: false
      matrix:
        arch: ['x86_64', 'arm64']
        os: ['ubuntu:20.04', 'debian:10']
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Test install.sh in Docker container
        run: |
          echo "Testing on ${{ matrix.os }} (${{ matrix.arch }})"
          docker buildx build --load \
            --build-arg BASE_IMAGE=${{ matrix.os }} \
            --platform=linux/${{ matrix.arch }} \
            -t test-install:${{ matrix.arch }} \
            -f .github/Dockerfile.test .
          docker run --rm test-install:${{ matrix.arch }} help