name: GitHub Release CI
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: yarn --ignore-scripts --frozen-lockfile --non-interactive
      - name: Build binaries
        run: yarn build
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: contains(github.ref, '-')
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: build/*
